name: some action
on:
  workflow_dispatch:
jobs:
  starter:
    runs-on: ubuntu-latest
    steps:
      - name: Map branch to DEMO environment
        uses: iamtheyammer/branch-env-vars@master
        with:
          VAR: |
            a:1
            b:2
      - name: Echo
        run: echo "${{env.VAR}}"