name: starter
on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/5 * * * *'
jobs:
  starter:
    strategy:
      matrix:
        ref: [ a, b ]
    runs-on: ubuntu-latest
    steps:
      - name: "Invoke reindex on demo ${{matrix.ref}}"
        uses: ./.github/workflows/some_action.yml@${{matrix.ref}}